package obspackage;


import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ibrahimsengun
 */
public class AkademisyenEkrani extends javax.swing.JFrame {

    SQLBaglanti sql = new SQLBaglanti();
    private String ANo;
    Akademisyen akademisyen = null;
    
    public AkademisyenEkrani(String ANo) {
        initComponents();
        this.ANo = ANo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_akademisyenad = new javax.swing.JLabel();
        btn_Geri = new javax.swing.JButton();
        btn_DersEkle = new javax.swing.JButton();
        btn_OgrenciGoruntule = new javax.swing.JButton();
        btn_NotGir = new javax.swing.JButton();
        pane_DersEkle = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_DersEkleAd = new javax.swing.JTextField();
        tf_DersEkleKod = new javax.swing.JTextField();
        tf_DersEkleKredi = new javax.swing.JTextField();
        btn_DersEkleNoOlustur = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_DersEkleNo = new javax.swing.JTextField();
        btn_DersEkleEkle = new javax.swing.JButton();
        pane_OgrLisele = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_DersListele = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_OgrenciListe = new javax.swing.JTable();
        pane_NotGir = new javax.swing.JLayeredPane();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        cb_NotGirOgr = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        cb_NotGirDers = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        btn_NotGirGuncelle = new javax.swing.JButton();
        tf_NotGirVize = new javax.swing.JTextField();
        tf_NotGirFinal = new javax.swing.JTextField();
        tf_NotGirHarf = new javax.swing.JTextField();
        btn_HarfNotuHesapla = new javax.swing.JButton();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        lbl_SecilenDers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_akademisyenad.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        lbl_akademisyenad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile.png"))); // NOI18N

        btn_Geri.setBackground(new java.awt.Color(255, 255, 255));
        btn_Geri.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_Geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        btn_Geri.setText("Geri");
        btn_Geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeriActionPerformed(evt);
            }
        });

        btn_DersEkle.setBackground(new java.awt.Color(255, 255, 255));
        btn_DersEkle.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btn_DersEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_1.png"))); // NOI18N
        btn_DersEkle.setText("Ders Ekle");
        btn_DersEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DersEkleActionPerformed(evt);
            }
        });

        btn_OgrenciGoruntule.setBackground(new java.awt.Color(255, 255, 255));
        btn_OgrenciGoruntule.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btn_OgrenciGoruntule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        btn_OgrenciGoruntule.setText("<html>" +"Öğrenci <br> Görüntüle" + "</html>");
        btn_OgrenciGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OgrenciGoruntuleActionPerformed(evt);
            }
        });

        btn_NotGir.setBackground(new java.awt.Color(255, 255, 255));
        btn_NotGir.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btn_NotGir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modify.png"))); // NOI18N
        btn_NotGir.setText("Not Gir");
        btn_NotGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NotGirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setText("Ders Ekle");

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText("Ders Adı:");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Ders Kodu: ");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Kredisi:");

        tf_DersEkleAd.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        tf_DersEkleKod.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        tf_DersEkleKredi.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        btn_DersEkleNoOlustur.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_DersEkleNoOlustur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        btn_DersEkleNoOlustur.setText("Numara Oluştur");
        btn_DersEkleNoOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DersEkleNoOlusturActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("Ders Numarası:");

        tf_DersEkleNo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        btn_DersEkleEkle.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_DersEkleEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        btn_DersEkleEkle.setText("Ders Ekle");
        btn_DersEkleEkle.setEnabled(false);
        btn_DersEkleEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DersEkleEkleActionPerformed(evt);
            }
        });

        pane_DersEkle.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(tf_DersEkleAd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(tf_DersEkleKod, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(tf_DersEkleKredi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(btn_DersEkleNoOlustur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(tf_DersEkleNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_DersEkle.setLayer(btn_DersEkleEkle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pane_DersEkleLayout = new javax.swing.GroupLayout(pane_DersEkle);
        pane_DersEkle.setLayout(pane_DersEkleLayout);
        pane_DersEkleLayout.setHorizontalGroup(
            pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_DersEkleLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_DersEkleNo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(tf_DersEkleAd)
                    .addComponent(tf_DersEkleKredi, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(tf_DersEkleKod, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(btn_DersEkleNoOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DersEkleEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_DersEkleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(239, 239, 239))
        );
        pane_DersEkleLayout.setVerticalGroup(
            pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_DersEkleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_DersEkleAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_DersEkleKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_DersEkleKredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_DersEkleNoOlustur)
                .addGap(18, 18, 18)
                .addGroup(pane_DersEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_DersEkleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_DersEkleEkle)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setText("Öğrenci Listesi");

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel7.setText("Ders:");

        cb_DersListele.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        tbl_OgrenciListe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tbl_OgrenciListe.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jScrollPane2.setViewportView(tbl_OgrenciListe);

        pane_OgrLisele.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_OgrLisele.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_OgrLisele.setLayer(cb_DersListele, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_OgrLisele.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pane_OgrLiseleLayout = new javax.swing.GroupLayout(pane_OgrLisele);
        pane_OgrLisele.setLayout(pane_OgrLiseleLayout);
        pane_OgrLiseleLayout.setHorizontalGroup(
            pane_OgrLiseleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_OgrLiseleLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_OgrLiseleLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(pane_OgrLiseleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pane_OgrLiseleLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cb_DersListele, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        pane_OgrLiseleLayout.setVerticalGroup(
            pane_OgrLiseleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_OgrLiseleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(pane_OgrLiseleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_DersListele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        jLabel8.setText("Seçilen Ders:");

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel9.setText("Öğrenci:");

        cb_NotGirOgr.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        cb_NotGirOgr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel10.setText("Ders:");

        cb_NotGirDers.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        cb_NotGirDers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_NotGirDers.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel11.setText("Harf:");

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel12.setText("Vize:");

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel13.setText("Final:");

        btn_NotGirGuncelle.setBackground(new java.awt.Color(255, 255, 255));
        btn_NotGirGuncelle.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_NotGirGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modify.png"))); // NOI18N
        btn_NotGirGuncelle.setText("Not Gir");
        btn_NotGirGuncelle.setEnabled(false);
        btn_NotGirGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NotGirGuncelleActionPerformed(evt);
            }
        });

        tf_NotGirVize.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N

        tf_NotGirFinal.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N

        tf_NotGirHarf.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        tf_NotGirHarf.setEnabled(false);

        btn_HarfNotuHesapla.setBackground(new java.awt.Color(255, 255, 255));
        btn_HarfNotuHesapla.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        btn_HarfNotuHesapla.setText("Harf Notu Hesapla");
        btn_HarfNotuHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HarfNotuHesaplaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel14.setText("Not Gir");

        lbl_SecilenDers.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        lbl_SecilenDers.setText("Seçilmedi");

        pane_NotGir.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(cb_NotGirOgr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(cb_NotGirDers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(btn_NotGirGuncelle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(tf_NotGirVize, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(tf_NotGirFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(tf_NotGirHarf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(btn_HarfNotuHesapla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pane_NotGir.setLayer(lbl_SecilenDers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pane_NotGirLayout = new javax.swing.GroupLayout(pane_NotGir);
        pane_NotGir.setLayout(pane_NotGirLayout);
        pane_NotGirLayout.setHorizontalGroup(
            pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_NotGirLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_NotGirLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btn_NotGirGuncelle))
                    .addGroup(pane_NotGirLayout.createSequentialGroup()
                        .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pane_NotGirLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cb_NotGirOgr, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pane_NotGirLayout.createSequentialGroup()
                                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_NotGirDers, 0, 300, Short.MAX_VALUE)
                                    .addComponent(tf_NotGirVize)
                                    .addComponent(tf_NotGirFinal)
                                    .addComponent(tf_NotGirHarf)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pane_NotGirLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_SecilenDers)))
                        .addGap(18, 18, 18)
                        .addComponent(btn_HarfNotuHesapla)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_NotGirLayout.createSequentialGroup()
                    .addContainerGap(319, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(295, 295, 295)))
        );
        pane_NotGirLayout.setVerticalGroup(
            pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_NotGirLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cb_NotGirOgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_NotGirDers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_SecilenDers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_NotGirVize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_NotGirFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btn_HarfNotuHesapla))
                .addGap(18, 18, 18)
                .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_NotGirHarf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btn_NotGirGuncelle)
                .addGap(18, 18, 18))
            .addGroup(pane_NotGirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_NotGirLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel14)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_akademisyenad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 703, Short.MAX_VALUE)
                .addComponent(btn_Geri)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_DersEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_OgrenciGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NotGir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(170, Short.MAX_VALUE)
                    .addComponent(pane_DersEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(170, Short.MAX_VALUE)
                    .addComponent(pane_OgrLisele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(170, Short.MAX_VALUE)
                    .addComponent(pane_NotGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_DersEkle)
                .addGap(18, 18, 18)
                .addComponent(btn_OgrenciGoruntule)
                .addGap(18, 18, 18)
                .addComponent(btn_NotGir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Geri)
                    .addComponent(lbl_akademisyenad))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pane_DersEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pane_OgrLisele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pane_NotGir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        sql.Baglan();
        try {
            lbl_akademisyenad.setText(sql.getAd(ANo, "akademisyen"));
            akademisyen = sql.GetAkademisyen(ANo);
        } catch (SQLException ex) {
            Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pane_DersEkle.setVisible(false);
        pane_OgrLisele.setVisible(false);
        pane_NotGir.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btn_GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeriActionPerformed
        GirisEkrani girisEkrani = new GirisEkrani();
        setVisible(false);
        girisEkrani.setVisible(true);
    }//GEN-LAST:event_btn_GeriActionPerformed

    private void btn_DersEkleNoOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DersEkleNoOlusturActionPerformed
        try {
            String DNo = sql.DersSayisi();
            
            if(!tf_DersEkleAd.getText().equals("") && !tf_DersEkleKod.getText().equals("") && !tf_DersEkleKredi.getText().equals("")){
                btn_DersEkleEkle.setEnabled(true);
                tf_DersEkleNo.setText(DNo);
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Lütfen gerekli alanları giriniz.");
        } catch (SQLException ex) {
            Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_DersEkleNoOlusturActionPerformed

    private void btn_DersEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DersEkleActionPerformed
        pane_OgrLisele.setVisible(false);
        pane_NotGir.setVisible(false);
        
        if(pane_DersEkle.isVisible()) {
            pane_DersEkle.setVisible(false);
        }
        else {
            pane_DersEkle.setVisible(true);
        }
    }//GEN-LAST:event_btn_DersEkleActionPerformed

    private void btn_DersEkleEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DersEkleEkleActionPerformed
        try {
            sql.DersEkle(tf_DersEkleNo.getText(), tf_DersEkleAd.getText(), tf_DersEkleKod.getText(), tf_DersEkleKredi.getText(), akademisyen.getBNo());
            JOptionPane.showMessageDialog(rootPane, "Ders başarıyla eklendi.");
            
            tf_DersEkleAd.setText("");
            tf_DersEkleKod.setText("");
            tf_DersEkleKredi.setText("");
            tf_DersEkleNo.setText("");
            btn_DersEkleEkle.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_DersEkleEkleActionPerformed

    private void btn_OgrenciGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OgrenciGoruntuleActionPerformed
        pane_DersEkle.setVisible(false);
        pane_NotGir.setVisible(false);
        
        if(pane_OgrLisele.isVisible()) {
            pane_OgrLisele.setVisible(false);
        }
        else {
            pane_OgrLisele.setVisible(true);
            tbl_OgrenciListe.setVisible(false);
            try {
                cb_DersListele.setModel(new javax.swing.DefaultComboBoxModel<>(sql.DersListesi(akademisyen.getBNo())));
            } catch (SQLException ex) {
                Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String[] head = new String[5];
            head[0] = "Okul No";
            head[1] = "İsim";
            head[2] = "Vize";
            head[3] = "Final";
            head[4] = "Harf";
            
            cb_DersListele.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        String DNo = getCBNo(cb_DersListele);
                        tbl_OgrenciListe.setModel(new javax.swing.table.DefaultTableModel(
                                sql.getTumOgrNotMatris(akademisyen.getBNo(), DNo),
                                head
                        ));
                        tbl_OgrenciListe.setVisible(true);
                        resizeColumnWidth(tbl_OgrenciListe);
                    } catch (SQLException ex) {
                        Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
            
        }
    }//GEN-LAST:event_btn_OgrenciGoruntuleActionPerformed

    private void btn_NotGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NotGirActionPerformed
        pane_DersEkle.setVisible(false);
        pane_OgrLisele.setVisible(false);
        
        
        if(pane_NotGir.isVisible()) {
            pane_NotGir.setVisible(false);
        }
        else {
            pane_NotGir.setVisible(true);
            try {
                
                cb_NotGirOgr.setModel(new javax.swing.DefaultComboBoxModel<>(sql.OgrenciListeBolumeGore(akademisyen.getBNo())));
                cb_NotGirOgr.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        try {

                            cb_NotGirDers.setModel(new javax.swing.DefaultComboBoxModel<>(sql.OgrDersNotListele(getCBNo(cb_NotGirOgr))));
                            cb_NotGirDers.addActionListener(new ActionListener() {
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    lbl_SecilenDers.setText(cb_NotGirDers.getSelectedItem().toString());
                                }
                            });
                            cb_NotGirDers.setEnabled(true);
                        } catch (SQLException ex) {
                            Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            } catch (SQLException ex) {
                Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btn_NotGirActionPerformed

    private void btn_HarfNotuHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HarfNotuHesaplaActionPerformed
        String vize, finalN, harf = null;
        double ortalama;
        
        if(!tf_NotGirVize.getText().equals("") && !tf_NotGirFinal.getText().equals(""))
        {
            vize = tf_NotGirVize.getText();
            finalN = tf_NotGirFinal.getText();
            ortalama = Integer.parseInt(vize) * 0.4 + Integer.parseInt(finalN) * 0.6;
            
            if(ortalama <= 39)
                harf = "FF";
            else if(ortalama <= 59)
                harf = "DD";
            else if(ortalama <= 64)
                harf = "DC";
            else if(ortalama <= 74)
                harf = "CC";
            else if(ortalama <= 79)
                harf = "CB";
            else if(ortalama <= 84)
                harf = "BB";
            else if(ortalama <= 89)
                harf = "BA";
            else if(ortalama <= 100)
                harf = "AA";
            
            tf_NotGirHarf.setText(harf);
            btn_NotGirGuncelle.setEnabled(true);
        }
    }//GEN-LAST:event_btn_HarfNotuHesaplaActionPerformed

    private void btn_NotGirGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NotGirGuncelleActionPerformed
        try {
            sql.OgrenciNotGir(getCBNo(cb_NotGirOgr), tf_NotGirVize.getText(), tf_NotGirFinal.getText(), tf_NotGirHarf.getText());
            JOptionPane.showMessageDialog(rootPane, "Öğrencinin notu başarıyla girilmiştir.");
            
            cb_NotGirOgr.setSelectedIndex(0);
            cb_NotGirDers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
            cb_NotGirDers.setEnabled(false);
            btn_NotGirGuncelle.setEnabled(false);
            tf_NotGirFinal.setText("");
            tf_NotGirHarf.setText("");
            tf_NotGirVize.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(AkademisyenEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_NotGirGuncelleActionPerformed

    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    
    public String getCBNo(JComboBox combobox) {
        String s = combobox.getSelectedItem().toString().trim().substring(0, combobox.getSelectedItem().toString().trim().indexOf("-")).trim();
        return s;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DersEkle;
    private javax.swing.JButton btn_DersEkleEkle;
    private javax.swing.JButton btn_DersEkleNoOlustur;
    private javax.swing.JButton btn_Geri;
    private javax.swing.JButton btn_HarfNotuHesapla;
    private javax.swing.JButton btn_NotGir;
    private javax.swing.JButton btn_NotGirGuncelle;
    private javax.swing.JButton btn_OgrenciGoruntule;
    private javax.swing.JComboBox<String> cb_DersListele;
    private javax.swing.JComboBox<String> cb_NotGirDers;
    private javax.swing.JComboBox<String> cb_NotGirOgr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_SecilenDers;
    private javax.swing.JLabel lbl_akademisyenad;
    private javax.swing.JLayeredPane pane_DersEkle;
    private javax.swing.JLayeredPane pane_NotGir;
    private javax.swing.JLayeredPane pane_OgrLisele;
    private javax.swing.JTable tbl_OgrenciListe;
    private javax.swing.JTextField tf_DersEkleAd;
    private javax.swing.JTextField tf_DersEkleKod;
    private javax.swing.JTextField tf_DersEkleKredi;
    private javax.swing.JTextField tf_DersEkleNo;
    private javax.swing.JTextField tf_NotGirFinal;
    private javax.swing.JTextField tf_NotGirHarf;
    private javax.swing.JTextField tf_NotGirVize;
    // End of variables declaration//GEN-END:variables
}
